ALTER TABLE mark DROP CONSTRAINT MARK_STUDENT_ID_FKEY;
ALTER TABLE payment DROP CONSTRAINT PAYMENT_STUDENT_ID_FKEY;

DELETE FROM student WHERE id IN (
    SELECT student_id
    FROM mark
    WHERE mark < 4
);

DELETE FROM payment WHERE student_id IN (
    SELECT student_id
    FROM mark
    WHERE mark < 4
);

DELETE FROM mark WHERE mark <4;

ALTER TABLE mark SET CONSTRAINT MARK_STUDENT_ID_FKEY;
ALTER TABLE payment SET CONSTRAINT PAYMENT_STUDENT_ID_FKEY;