ALTER TABLE mark DROP CONSTRAINT MARK_STUDENT_ID_FKEY;
ALTER TABLE payment DROP CONSTRAINT PAYMENT_STUDENT_ID_FKEY;

DELETE FROM student WHERE id IN (
    SELECT student_id
    FROM mark
    WHERE mark < 4
);

DELETE FROM payment WHERE student_id IN (
    SELECT student_id
    FROM mark
    WHERE mark < 4
);

DELETE FROM mark WHERE mark <4;

ALTER TABLE mark ADD CONSTRAINT MARK_STUDENT_ID_FKEY FOREIGN KEY (student_id) REFERENCES student(id);
ALTER TABLE payment ADD CONSTRAINT PAYMENT_STUDENT_ID_FKEY FOREIGN KEY (student_id) REFERENCES student(id);;
